apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: gha-runner-controller
  namespace: gha-runner-controller
resources:
  - namespace.yaml
  #- repository.yaml
  #- release.yaml
