apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../apps/sealed-secrets/
  - ../apps/cert-manager/
  - ../apps/metallb/
  - ../apps/mariadb-operator/
  - ../apps/mysql-operator/
