apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: gitea
  namespace: gitea
resources:
  - sealed-secret.gitea-admin.yaml
  - sealed-secret.star.pekware.club.yaml
  - pvc.yaml
  - ../../base/gitea/
patches:
  - path: release.yaml
    target:
      kind: HelmRelease
