apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - external-dns/
  - ingress-nginx/
  - cert-manager/
  #- kube-prometheus-stack/
  - minio-vanilla/
  - bitnami-redis/
  - metallb/
  - csi-driver-nfs/
  ##- mysql-innodbcluster/
  - syncserver/
  ##- bitnami-wordpress/
  #- gha-runner-controller
  #- arc-runners/
